In [1]:
import pandas as pd
import numpy as np

In [3]:
coldChainDF = pd.read_csv("data/coldchain_sensors.csv")

In [5]:
coldChainDF.head()

,trip_id,minute,t_air_c,rh_pct,t_ambient_c,rh_ambient_pct,door_open,vehicle_moving,compressor_on,defrost_on,hour_of_day,split
0,TRIP_0000,0,5.7,86.4,31.8,43.7,0,1,1,0,7.273,val
1,TRIP_0000,1,5.2,88.4,31.8,44.5,0,1,1,0,7.289,val
2,TRIP_0000,2,5.3,85.4,31.6,43.4,0,1,1,0,7.306,val
3,TRIP_0000,3,5.0,85.3,31.7,43.3,0,1,1,0,7.323,val
4,TRIP_0000,4,4.9,84.6,32.1,45.1,0,1,1,0,7.339,val

In [6]:
trainData = coldChainDF[coldChainDF["split"] == "train"]
valData = coldChainDF[coldChainDF["split"] == "val"]

In [8]:
trainData.head()

,trip_id,minute,t_air_c,rh_pct,t_ambient_c,rh_ambient_pct,door_open,vehicle_moving,compressor_on,defrost_on,hour_of_day,split
519,TRIP_0001,0,9.7,87.4,39.0,46.5,0,1,1,0,15.805,train
520,TRIP_0001,1,9.8,85.9,38.4,46.0,0,1,1,0,15.822,train
521,TRIP_0001,2,9.3,88.2,38.6,46.8,0,1,1,0,15.839,train
522,TRIP_0001,3,9.5,85.7,38.8,45.7,0,1,1,0,15.855,train
523,TRIP_0001,4,9.5,85.9,38.6,48.4,0,1,1,0,15.872,train

In [9]:
valData.head()

,trip_id,minute,t_air_c,rh_pct,t_ambient_c,rh_ambient_pct,door_open,vehicle_moving,compressor_on,defrost_on,hour_of_day,split
0,TRIP_0000,0,5.7,86.4,31.8,43.7,0,1,1,0,7.273,val
1,TRIP_0000,1,5.2,88.4,31.8,44.5,0,1,1,0,7.289,val
2,TRIP_0000,2,5.3,85.4,31.6,43.4,0,1,1,0,7.306,val
3,TRIP_0000,3,5.0,85.3,31.7,43.3,0,1,1,0,7.323,val
4,TRIP_0000,4,4.9,84.6,32.1,45.1,0,1,1,0,7.339,val

In [10]:
from sklearn.preprocessing import StandardScaler

stdScl = StandardScaler()